Feature: envios

  Scenario Outline: Make a shipment
    Given A user login in Self-Services web page with credentials "<organization>" "<userName>" "<password>"
    When the user make shipment introducing "<shippingType>" "<locationRecollect>" "<typeOfHousing>" "<reference>" "<shippingWeight>" "<schedule>" "<nameThatRecollect>" "<phoneThatRecollect>" "<emailThatRecollect>" "<locationReceives>" "<typeOfHousingReceives>" "<nameThatReceives>" "<phoneThatReceives>" "<emailThatReceives>" "<referenceReceives>" "<cod>"
    Then the user print the shipping guide

    Examples: 
      |organization| userName                     | password      | shippingType | locationRecollect                                                                       | typeOfHousing | reference      | shippingWeight | schedule              | nameThatRecollect | phoneThatRecollect | emailThatRecollect   | locationReceives                                                                                                                | typeOfHousingReceives | nameThatReceives | phoneThatReceives | emailThatReceives          | referenceReceives |cod     |
      |Test        | mmhpruebas40@gmail.com       | 99Minutos.com | Next day     | calle 6 num 145 col nezahualcoyotl 57420                                                | Residencial   | P99 M COD      | De 2 a 3 kg    | Lo mas pronto posible | P99 M COD         |         5633561865 | jess_arn18@gmail.com | Avenida Presidente Masaryk 29-piso 3, Chapultepec Morales, Polanco V sección, Ciudad de México, Ciudad de México, México, 11560 | Residencial           | Pruebas QA P99   |      57562877     | jesus.bernal@99minutos.com | Guía para pruebas |1000    |
      |Test        | mmhpruebas40@gmail.com       | 99Minutos.com | Next day     | calle 6 num 145 col nezahualcoyotl 57420                                                | Residencial   | P99 M COD      | De 2 a 3 kg    | Lo mas pronto posible | P99 M nCOD        |         5633561865 | jess_arn18@gmail.com | Avenida Presidente Masaryk 29-piso 3, Chapultepec Morales, Polanco V sección, Ciudad de México, Ciudad de México, México, 11560 | Residencial           | Pruebas QA P99   |      57562877     | jesus.bernal@99minutos.com | Guía para pruebas |NA      |
      |Test        | mmhpruebas40@gmail.com       | 99Minutos.com | Next day     | calle 6 num 145 col nezahualcoyotl 57420                                                | Residencial   | P99 M COD      | Menos de 1 kg  | Lo mas pronto posible | P99 s COD         |         5633561865 | jess_arn18@gmail.com | Avenida Presidente Masaryk 29-piso 3, Chapultepec Morales, Polanco V sección, Ciudad de México, Ciudad de México, México, 11560 | Residencial           | Pruebas QA P99   |      57562877     | jesus.bernal@99minutos.com | Guía para pruebas |1000    |
      |Test        | mmhpruebas40@gmail.com       | 99Minutos.com | Next day     | calle 6 num 145 col nezahualcoyotl 57420                                                | Residencial   | P99 xs nCOD    | Menos de 1 kg  | Lo mas pronto posible | P99 xs nCOD       |         5633561865 | jess_arn18@gmail.com | La luminiteca, San Guillermo Mz19 Lt15, Sta. Úrsula Coapa, 04600 Ciudad de México, CDMX, México                                 | Residencial           | Pruebas QA P99   |      57562877     | jesus.bernal@99minutos.com | Guía para pruebas |NA      |
      |Test        | mmhpruebas40@gmail.com       | 99Minutos.com | Next day     | calle 6 num 145 col nezahualcoyotl 57420                                                | Residencial   | P99 xs COD     | Menos de 1 kg  | Lo mas pronto posible | P99 xs COD        |         5633561865 | jess_arn18@gmail.com | La luminiteca, San Guillermo Mz19 Lt15, Sta. Úrsula Coapa, 04600 Ciudad de México, CDMX, México                                 | Residencial           | Pruebas QA P99   |      57562877     | jesus.bernal@99minutos.com | Guía para pruebas |1000    |
      |Test        | mmhpruebas40@gmail.com       | 99Minutos.com | Next day     | calle 6 num 145 col nezahualcoyotl 57420                                                | Residencial   | P99 M nCOD     | De 2 a 3 kg    | Lo mas pronto posible | P99 M nCOD        |         5633561865 | jess_arn18@gmail.com | La luminiteca, San Guillermo Mz19 Lt15, Sta. Úrsula Coapa, 04600 Ciudad de México, CDMX, México                                 | Residencial           | Pruebas QA P99   |      57562877     | jesus.bernal@99minutos.com | Guía para pruebas |NA      |

      